security:
  encoders:
    AcMarche\MaintenanceShop\Entity\User:
      algorithm: auto

  providers:
    sql_provider:
      entity:
        class: AcMarche\MaintenanceShop\Entity\User
        property: username
  firewalls:
    main:
      anonymous: lazy
      provider: sql_provider
      guard:
        authenticators:
          - AcMarche\MaintenanceShop\Security\CommandeAuthenticator
      logout:
        path: app_logout
