security:
  password_hashers:
    AcMarche\MaintenanceShop\Entity\User:
      algorithm: auto

  providers:
    sql_provider:
      entity:
        class: AcMarche\MaintenanceShop\Entity\User
        property: username
  firewalls:
    main:
      lazy: true
      provider: sql_provider
      custom_authenticators:
        - AcMarche\MaintenanceShop\Security\CommandeAuthenticator
      logout:
        path: app_logout
